./bin/bangor_welsh/run-kfold-cv-tl-macsen.sh 1
./bin/bangor_welsh/run-kfold-cv-tl-macsen.sh 2
./bin/bangor_welsh/run-kfold-cv-tl-macsen.sh 3
./bin/bangor_welsh/run-kfold-cv-tl-macsen.sh 4
./bin/bangor_welsh/run-kfold-cv-tl-macsen.sh 5
./bin/bangor_welsh/run-kfold-cv-tl-macsen.sh 6
./bin/bangor_welsh/run-kfold-cv-tl-macsen.sh 7
./bin/bangor_welsh/run-kfold-cv-tl-macsen.sh 8
./bin/bangor_welsh/run-kfold-cv-tl-macsen.sh 9
./bin/bangor_welsh/run-kfold-cv-tl-macsen.sh 10
