#!/bin/bash
# Usage: ./scw run-macsen.sh

export DEEPSPEECH_IMG=techiaith_deepspeech.simg
export DEEPSPEECH_RUN=$1
export DEEPSPEECH_DATA=../../data
export DEEPSPEECH_BIN=../bin
export DEEPSPEECH_OUTPUT=/scratch/scw1097/deepspeech_cy

sbatch run.slurm
